USE ventas_jugos;

CREATE TABLE tb_vendedor(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR (50) NULL,
COMISION FLOAT NULL,
FECHA_ADMISION DATE NULL,
DE_VACACIONES BIT(1) NULL,
PRIMARY KEY (MATRICULA)
);

CREATE TABLE tb_producto(
CODIGO VARCHAR (10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMAÑO VARCHAR(50) NULL,
ENVASE VARCHAR(50) NULL,
PRECI_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);


CREATE TABLE tb_clientes(
DNI VARCHAR (25) NOT NULL,
NOMBRE VARCHAR (100) NULL,
DIRECCION VARCHAR (100) NULL,
BARRIO VARCHAR(100) NULL,
CIUDAD VARCHAR (50) NULL,
ESTADO VARCHAR (50) NULL,
CP VARCHAR (8) NULL,
FECHA_NACIMIENTO DATE DEFAULT NULL,
EDAD INT (2) NULL,
SEXO VARCHAR(1) NULL,
LIMITE_CREDITO FLOAT DEFAULT NULL,
VOLUMEN_COMPRA FLOAT DEFAULT NULL,
PRIMERA_COMPRA BIT(1) NULL,
PRIMARY KEY(DNI)
 );